package app.tool.service.application.helper;

public enum ReportReason {
    INAPPROPRIATE_PHOTO,
    INAPPROPRIATE_NAME,
    STOLEN_PHOTO,
    HARASSMENT,
    SPAM_OR_SCAM,
    IMPERSONATION,
    HATE_SPEECH,
    THREATENING_BEHAVIOR,
    FAKE_ACCOUNT,
    DISCRIMINATION,
    BULLYING,
    VIOLENCE,
    COPYRIGHT_INFRINGEMENT,
    PRIVACY_VIOLATION,
    ILLEGAL_ACTIVITY,
    UNWANTED_ADVANCES,
    MISINFORMATION,
    SUSPICIOUS_ACTIVITY,
    OTHER;

}